### ISSUE TITLE
navigation: true option not working at all!

### ISSUE THREAD

**Issue by mozafarfahimi** [alvarotrigo/vue-fullpage.js#168] opened 2020-05-09 09:12 UTC
I'm using nuxt and registering vue-fullpage in plugins and the main feature (fullpage scrolling) is working but the option navigation: true not working for me.

**Comment by alvarotrigo** [comment] 2020-05-09 17:22
Seems to be working fine on the codesandbox provided in the docs:
https://codepen.io/alvarotrigo/pen/zpQmwq

Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by mozafarfahimi** [comment] 2020-05-09 19:38
here is the index.vue file in pages where i want fullpage for my home page
and i've registered full-page component as a plugin in in plugins folder.
the snap scrolling feature and scrollbar: false are just working fine but i can't get the spans for navigation to work!

<template>
  <full-page :options="options" id="fullpage">
    <div class="section">
      <h3>Section 1</h3>
    </div>
    <div class="section">
      <h3>Section 2</h3>
    </div>
    <div class="section">
      <h3>Section 3</h3>
    </div>
  </full-page>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      options: {
        scrollBar: false,
        navigation: true,
        sectionsColor: [
          "#41b883",
          "#ff5f45",
          "#0798ec",
          "#fec401",
          "#1bcee6",
          "#ee1a59",
          "#2c3e4f",
          "#ba5be9",
          "#b4b8ab"
        ]
      }
    };
  }
};
</script>

**Comment by mozafarfahimi** [comment] 2020-05-09 19:39
here is the index.vue file in pages where i want fullpage for my home page
and i've registered full-page component as a plugin in in plugins folder.
the snap scrolling feature and scrollbar: false are just working fine but i can't get the spans for navigation to work!

`<template>
  <full-page :options="options" id="fullpage">
    <div class="section">
      <h3>Section 1</h3>
    </div>
    <div class="section">
      <h3>Section 2</h3>
    </div>
    <div class="section">
      <h3>Section 3</h3>
    </div>
  </full-page>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      options: {
        scrollBar: false,
        navigation: true,
        sectionsColor: [
          "#41b883",
          "#ff5f45",
          "#0798ec",
          "#fec401",
          "#1bcee6",
          "#ee1a59",
          "#2c3e4f",
          "#ba5be9",
          "#b4b8ab"
        ]
      }
    };
  }
};
</script>`

**Comment by alvarotrigo** [comment] 2020-05-16 13:44
I'll wait a codepn or a codesanbox with the reproduction.

**Comment by MrDWilson** [comment] 2020-06-03 14:46
[I feel this could very well be a duplicate of this issue, with the CSS file not being imported.](https://github.com/alvarotrigo/vue-fullpage.js/issues/118)

**Comment by alvarotrigo** [comment] 2020-06-04 10:03
Thanks for pointing that out @MrDWilson ! 👍

**Comment by alvarotrigo** [comment] 2022-05-10 16:52
I'll close the issue as it seems it got resolved.

**Closed by alvarotrigo** 2022-05-10 16:52 UTC
Labels: Reproduction required
