### ISSUE TITLE
Section doesn't move on clicking the Navigation button

### ISSUE THREAD

**Issue by workforv** [alvarotrigo/vue-fullpage.js#47] opened 2018-08-14 09:48 UTC
**Issue:**
I've created a vue project (v-cli webpack project) which has two page(A an B,both vue-router components) .In each page I use fullpage component .

Now the scenario is, first I change route from A page to B page via clicking one button, then I realized no matter how I click the circle spot button in the right hand-side, the page won't scroll at all.

Any help would be greatly appreciated, thanks! 

# a.vue

```vue
<template>
  <full-page  ref="fullpagea" :options="options" id="fullpagea" >
    <div class="section">
    </div>
    <div class="section" >
    </div>
  </full-page>
</template>
<script>
export default {
  name: "testa",
  data() {
    return {
      options: {
        anchors: ["a1", "a2"],
        sectionsColor: ["blue", "#f6f6f9"],
        scrollingSpeed: 600,
        navigation: true,
      }
    };
  }
};
</script>

```

# b.vue

```vue
<template>
  <full-page  ref="fullpageb" :options="options" id="fullpageb" >
    <div class="section">
    </div>
    <div class="section" >
    </div>
  </full-page>
</template>
<script>
export default {
  name: "testb",
  data() {
    return {
      options: {
        anchors: ["b1", "b2"],
        sectionsColor: ["red", "blue"],
        scrollingSpeed: 600,
        navigation: true,
      }
    };
  }
};
</script>
```

# router/index.js

```js
import Vue from 'vue'
import Router from 'vue-router'
import pA from '@/components/a'
import pB from '@/components/b'
Vue.use(Router)
export default new Router({
  routes: [
    {
      path: '/',
      name: 'pa',
      component: pA
    },
    {
      path: '/b',
      name: 'pb',
      component: pB
    }
  ]
})

```

# App.vue

```vue
<template>
  <div id="app">
    <div style="position:absolute;height:100px;background:white;width:100%;z-index:100">
      <router-link  :to="{path:'/'}"  >one </router-link> 
      <router-link  :to="{path:'/b'}"  >two </router-link> 
    </div>
    <router-view/>
  </div>
</template>
<script>
export default {
  name: 'App'
}
</script>
<style>
html,body{
  width:100%;
  height:100%;
}
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  height:100%
}
</style>
```
Version

**macOS:** 10.12.6 

**Chrome:** 67.0.3396.99 

**Vue CLI:** 2.9.6

**Vue:** 2.5.2

**Vue-rouer:** 3.0.1

**Vue-Fullpage.js:** 0.0.5

**Comment by alvarotrigo** [comment] 2018-08-14 09:53
Seems to be working perfectly for me. Check this example:
http://jsfiddle.net/a2n4uoht/1/

**Comment by alvarotrigo** [comment] 2018-08-14 09:55
Please try to provide an isolated reproduction. With a single JS file and that ideally you can reproduce in jsfiddle or codepen or even sandbox.

**Comment by workforv** [comment] 2018-08-14 10:33
Here's the reproduction [http://jsfiddle.net/pankzg48/1/](url) Click "Go to B" link then try to click the navigation button you might find the page B won't scoll

**Comment by alvarotrigo** [comment] 2018-08-14 10:55
Right! Thanks for that!
That's actually a fullPage.js bug and not a vue-fullpage.js issue. I'll check it out!

**Comment by alvarotrigo** [comment] 2018-08-15 09:48
I've fixed it on the dev branch of the fullPage.js repository. It will get merged on the next release.
Meanwhile, please feel free to replace the fullPage.js file or the fullpage.extensions.min.js file in your `node_modules` folder to 3.0.3, [the one in the dev branch](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/src/fullpage.js).

**Comment by workforv** [comment] 2018-08-16 02:43
Great Thanks！of course it work ！ Can‘t wait for  the new release!

**Comment by maxrisk** [comment] 2018-09-17 07:04
Navigation button not work when my route changed, version 3.0.3 not work too, I don't know why. @alvarotrigo

**Comment by alvarotrigo** [comment] 2018-09-17 09:54
@maxrisk you'll have to open a new issue and provide an isolated reproduction on [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or codesandbox.

**Comment by maxrisk** [comment] 2018-09-18 02:36
https://github.com/alvarotrigo/vue-fullpage.js/issues/58#issue-361112912

**Comment by alvarotrigo** [comment] 2018-10-10 10:47
Fixed in vue-fullpage.js 0.0.6

**Closed by alvarotrigo** 2018-10-10 10:47 UTC
Labels: Fixed on dev, Reproduction required
