### ISSUE TITLE
Conditional custom component are dissapearing

### ISSUE THREAD

**Issue by kristijan97** [alvarotrigo/vue-fullpage.js#147] opened 2019-11-20 16:45 UTC
```
<template>
    <div id="app">
        <full-page ref="fullpage" :options="{}">
            <div class="section">
                <customA v-if="game"></customA>
                <customB v-else></customB>
                {{ game }}
                <button @click="changeGame">Test</button>
                <button @click="rebuild">rebuild</button>
            </div>
        </full-page>
    </div>
</template>

<script>
  export default {
    name: 'app',
    data: () => ({
      game: false
    }),
    methods: {
      changeGame() {
        this.game = !this.game;
      },
      rebuild() {
        this.$refs.fullpage.api.reBuild();
      }
    }
  }
</script>
```

- CustomA, CustomB are just components with p with some random text

When I click on the Test button (change value of this.game), the custom component disappears and never shows again. Initially, I found this issue when I put router-view inside fullpage component and I got Vue error.

Also, is it possible to put router-view inside fullpage component without problems?

**Comment by alvarotrigo** [comment] 2019-11-20 17:03
Please check this conversation:
https://github.com/alvarotrigo/vue-fullpage.js/issues/138

You'll need to use the dev branch version so far :)

**Comment by kristijan97** [comment] 2019-11-20 17:14
I saw that issue and I tried using the dev branch, but is not working.
Mine problem is different - I initially see custom component, but after a variable change, it disappears.
#dev branch

"dependencies": {
    "core-js": "^3.3.2",
    "vue": "^2.6.10",
    "vue-fullpage.js": "https://github.com/alvarotrigo/vue-fullpage.js.git#dev"
  },

**Comment by alvarotrigo** [comment] 2019-11-20 17:39
Can you please provide an isolated reproduction in [codepen](https://codepen.io/alvarotrigo/pen/zpQmwq) or [codesandbox](https://codesandbox.io/), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by kristijan97** [comment] 2019-11-20 19:13
I tried to reproduce online, but I was unable to select dev branch using codepen/codesandbox. Instead, I created small reproduction and uploaded. Here is the link:
https://www.dropbox.com/s/nzcrf0uja34tk2m/test1.zip?dl=0

**Comment by dobromir-hristov** [comment] 2019-11-20 19:29
Please use GitHub, don't upload to Dropbox

**Comment by kristijan97** [comment] 2019-11-21 21:32
Of course, https://github.com/kristijan97/Test1

**Comment by dobromir-hristov** [comment] 2019-11-21 21:33
I dont see full-page there

**Comment by kristijan97** [comment] 2019-11-21 21:40
package.json
"vue-fullpage.js": "https://github.com/alvarotrigo/vue-fullpage.js.git#dev"
I pulled directly from github, dev branch

**Comment by dobromir-hristov** [comment] 2019-11-21 21:41
![image](https://user-images.githubusercontent.com/9863944/69379100-6d91aa00-0cb8-11ea-914c-e3c6c5887593.png)

Please check thoroughly your code and come back. Closing for now.

**Comment by kristijan97** [comment] 2019-11-21 21:44
Wrong folder, try again

**Comment by dobromir-hristov** [comment] 2019-11-21 22:12
Yep I saw what you mean. It is a problem with Fullpage and Vue itself. Fullpage copies over the components and puts them back, but I think when Vue changes elements in the DOM, fullpage tries to re-render again, which doesnt really work :/

**Comment by dobromir-hristov** [comment] 2019-11-21 22:14
@alvarotrigo I honestly dont know how to deal with this :( I think we need to leave the main DOM nodes in tact and rather clone them and watch for changes?

**Comment by kristijan97** [comment] 2019-11-21 22:23
Maybe to convert html dom elements to vue's elements?
```
const elements = document.querySelectorAll( 'some-selector' );
for ( let i = 0; i < elements.length; i++ ) {
  const element = elements[ i ];
  const compiled = Vue.compile( element.outerHTML );
  new Vue( {
    el: element,
    render: compiled.render
  } );
}
```

Maybe that will not interfere with Vue?

**Comment by alvarotrigo** [comment] 2019-11-21 22:35
> @alvarotrigo I honestly dont know how to deal with this :( I think we need to leave the main DOM nodes in tact and rather clone them and watch for changes?

What's the issue with the current approach?

**Comment by dobromir-hristov** [comment] 2019-11-22 07:23
When Vue components get updated/swapped/re-rendered, they disappear from the DOM. I am not sure if it is because FullPage.js moves and copies stuff around or its something else. Try out the repo he attached and see what I mean.

**Comment by kristijan97** [comment] 2019-11-25 13:17
Hey guys, any feedback?

**Comment by alvarotrigo** [comment] 2019-11-26 11:12
> Hey guys, any feedback?

Not yet.

**Comment by kristijan97** [comment] 2019-12-13 15:42
Hey guys, any feedback?

**Comment by alvarotrigo** [comment] 2020-02-07 18:20
> Fullpage copies over the components and puts them back, but I think when Vue changes elements in the DOM, fullpage tries to re-render again, which doesnt really work :/

Because of this you mean?

```js
watch: {
      options: {
        deep: true,
        handler () {
          this.build()
        }
      }
```

**Comment by hung211097** [comment] 2022-03-08 14:22
I got this problem too when I used condition to render element. It did not appear when the variable is true

**Comment by alvarotrigo** [comment] 2022-03-09 13:26
@JonathanSchndr will the new version tackle this? 🤔

**Comment by JonathanSchndr** [comment] 2022-03-09 14:02
Much has changed next version, so it would be super if @hung211097 provides an isolated code sandbox to provoke the error. I would be happy to check this and provide a solution! Thanks a lot!

**Closed** 2022-05-17 16:02 UTC
Labels: help wanted, question
