### ISSUE TITLE
fullpage is not defined

### ISSUE THREAD

**Issue by SueIte** [alvarotrigo/vue-fullpage.js#37] opened 2018-07-25 08:16 UTC
Hi there!
Iam still new to Vue and Fullpage, after the fix Iam using 
"vue-fullpage.js": "0.0.3",

I want the FullpageJS only on one site (Index.vue) and not on all the other sites. So the localhost starts, but inside the browser i get that error message :"    

> bundle.js:73787 Uncaught ReferenceError: fullpage is not defined
    at Object.disposed (bundle.js:73787)
    at __webpack_require__ (bundle.js:69868)
    at Object.module.exports (bundle.js:73972)
    at __webpack_require__ (bundle.js:69868)
    at bundle.js:69914
    at bundle.js:69917
    at webpackUniversalModuleDefinition (bundle.js:69841)
    at Object.render (bundle.js:69848)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:22093)

I tried the Demo which was uploaded here and a different way like this Tutorial ( https://github.com/cheulong/vue-fullpage-scroll) but both seem to throw the same error.

Can you support me with integrating it? 

My code looks as followed:

**Main.js**
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueVideoPlayer from 'vue-video-player'
import $ from 'jquery';
import 'bootstrap/dist/js/bootstrap.min.js'
import VueFullPage from 'vue-fullpage.js'
import './assets/js/global.js'
import 'video.js/dist/video-js.css'

import App from './components/App.vue'
import About from './components/Sites/About.vue'
import Consult from './components/Sites/Consult.vue'
import Contact from './components/Sites/Contact.vue'
import Customers from './components/Sites/Customers.vue'
import Msgpia from './components/Sites/Msgpia.vue'
import Index from './components/Sites/Index.vue'

Vue.use(VueVideoPlayer)
Vue.use(VueRouter)
Vue.use(VueFullPage)

const routes = [
 {
     name: 'About',
     path: '/about',
     component: About
 },
 {
     name: 'Index',
     path: '/index',
     component: Index
 },
 {
     name: 'App',
     path: '/',
     component: App,
     redirect: '/index'
 },
 {
    name: 'Consult',
    path: '/consult',
    component: Consult
},
{
   name: 'Contact',
   path: '/contact',
   component: Contact
},
{
   name: 'Customers',
   path: '/customers',
   component: Customers
},
{
   name: 'Msgpia',
   path: '/msgpia',
   component: Msgpia
}
];

var router = new VueRouter({
  mode: 'history',
  linkActiveClass: 'active',
  routes: routes
});

new Vue(Vue.util.extend({ router }, App)).$mount('#app')
```
**index.html**

```
<!DOCTYPE html>
<html lang="de" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge; IE=11">
    <link rel="icon" type="image/vnd.microsoft.icon" href="logo-small.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.1/fullpage.min.css">

    <!--[if IE 9]>
    <script>window.alert("Your IE Version is not supported. Please update to Version 10 or higher")</script>
    <![endif]-->
    <!--[if lte IE 8]>
    <script>window.alert("Your IE Version is not supported. Please update to Version 10 or higher")</script>
    <![endif]-->
    <!--[if IE 7]>
    <script>window.alert("Your IE Version is not supported. Please update to Version 10 or higher")</script>
    <![endif]-->
    <title>My Homepage</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="bundle.js"></script>
  </body>
</html>

```
**Index.vue**
```
<template lang="html">
    <div id="fullpage" class="bgWhite">
        <full-page :options="options">
      <!-- erste Seite -->
      <div data-anchor="home" class="section container-fluid backgroundSurf">
          <div id="slide1" class="h-100 position-relative">
              <logo-small></logo-small>

              <div class="row">
                  <div id="slide1h1" class="col-sm-8">
                      <h1>Passion <br> für Versiche-rungssysteme</h1>
                  </div>
              </div>
              <div class="row pt-5">
                  <div class="offset-sm-1 col-sm-11 col-md-11 col-xl-8 textbox">
                      <p><span class="upperC">VERSICHERUNGS KNOW HOW | BERATUNG |</span></p>
                      <p><span class="upperC">USER EXPERIENCE& INTERFACE DESIGN |</span></p>
                      <p><span class="upperC">SOFTWARE DEVELOPING | msg.PIA |</span></p>
                      <p><span class="upperC">MALS | TIME2MARKET |  msg.CIA |</span></p>
                  </div>
              </div>
          </div>
      </div>
      <!-- erste Seite Ende -->
      <!-- zweite seite -->
      <div data-anchor="msgpia" class="section container-fluid bgGrey">
          <div id="slide2" class="h-100 position-relative">
              <logo-small></logo-small>

              <div class="row">
                  <div id="slide2h1" class="offset-xs-1 col-xs-8">
                      <h1 class="init">msg.PIA</h1>
                  </div>
              </div>
              <div class="row d-flex">
                  <div class="offset-xs-1 col-sm-10  col-md-10 col-lg-8 col-xl-6 textbox" style="align-self: center;">
                      <p><span class="upperC">Die prozessgestützte SAP Allsparten-</span></p>
                      <p><span class="upperC">Lösung für flexible, effiziente </span></p>
                      <p><span class="upperC">Bestandsführung.</span></p>
                  </div>
                  <div class="col-sm-4" style="align-self: center;">
                      <img data-src="/src/assets/img/kreuz.png" style="max-width:100%;" alt="" />
                  </div>
              </div>
              <div class="row">
                  <div class="offset-xs-1 col-sm-3 pt-5">
                      <a class="init" href="msgpia.html">Zur msg.PIA Webseite
                          <div class="orangeRect"></div>
                      </a>
                  </div>
              </div>
          </div>
      </div>
      <!-- zweite Seite Ende -->
    </full-page>
  </div>
</div>

</template>

<script>
import Footer from '../Modules/Footer/Footer.vue';
import LogoSmall from '../Modules/Logos/LogoSmall.vue';
import LogoWhite from '../Modules/Logos/LogoWhite.vue';
import VideoView from '../Modules/Media/VideoView.vue';


export default {
  data: function () {
    return {
        options: {
            navigation: true,
            anchors: ['home', 'msgpia', 'mals', 'malsVideo', 'kunden', 'kontakt'],
            navigationPosition: 'right',
            navigationTooltips: ['Home', 'msg.Pia', 'MALS', 'MALS Media', 'Unsere Kunden', 'Kontakt'],
            css3: true,
            verticalCentered: false,
            paddingTop: '50px',
            paddingBottom: '50px',
            sectionSelector: '.section'
        }
    }
  },
  components: {
      'logo-small' : LogoSmall,
      'logo-white' : LogoWhite,
      'video-view' : VideoView,
      Footer
  },
  methods:{

  }
}
</script>
```

**Comment by alvarotrigo** [comment] 2018-07-25 08:57
> I tried the Demo which was uploaded here

Which one? Which of them is throwing the error?
I don't think I see any error in neither "demos/stand-alone/index.html" or "demos/webpack/index.html"

**Comment by SueIte** [comment] 2018-07-25 09:32
No Iam unable to run "npm install" because of an error which changes every time

> npm ERR! path C:\Users\kuckes\Desktop\dev\vue-fullpage\demos\webpack\node_modules\.staging\vue-fullpage-6c1d6fa4\node_modules\@mrmlnc\readdir-enhanced
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall rename
> npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\kuckes\Desktop\dev\vue-fullpage\demos\webpack\node_modules\.staging\vue-fullpage-6c1d6fa4\node_modules\@mrmlnc\readdir-enhanced' -> 'C:\Users\kuckes\Desktop\dev\vue-fullpage\demos\webpack\node_modules\.staging\@mrmlnc\readdir-enhanced-9b048cb7'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent

**Comment by alvarotrigo** [comment] 2018-07-25 09:36
Ok, yeap, sounds like there's an issue there. 
Just remove "package-lock.json". Then run `npm install` again.

**Comment by SueIte** [comment] 2018-07-25 09:57
Thanks it was working now, upon opening the localhost i got:

> ./src/main.js
> Module not found: Error: Can't resolve 'vue-fullpage' in '..\demos\webpack\src'
>  @ ./src/main.js 2:0-39
>  @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by alvarotrigo** [comment] 2018-07-25 10:11
No need to open localhost. 
Just access `demos/webpack/index.html` and you should see it working now.

**Comment by alvarotrigo** [comment] 2018-07-25 10:11
after running the compiling commands to generate the dist files.

**Comment by SueIte** [comment] 2018-07-25 10:45
even then I get an error:

> Uncaught Error: Cannot find module "vue-fullpage"

**Comment by rikkipitt** [comment] 2018-07-25 10:55
Just to confirm, I get this error too with my set up with Rails/Webpacker...

**Comment by alvarotrigo** [comment] 2018-07-25 13:06
> even then I get an error:

Yeah, probably because of this line in `package.json`:

    "vue-fullpage": "../../"

You have to do `npm install` in the root folder too... 
I'll fix that later.

**Comment by alvarotrigo** [comment] 2018-07-25 15:56
Fixed on the dev branch.
It should be  `"vue-fullpage.js": "0.0.3"`

**Comment by SueIte** [comment] 2018-07-25 16:33
thank you it is working finally...
I see there have been made a few changes. Nonetheless I'd like to ask one more question. When using the afterLoad callback inside the options object - how can I still access the origin.index? It worked without Vue but using it inside Vue I get null if I want to access the origin variable - like that:

```
methods: {
        afterLoad: function (origin) {
            if (origin.index === 1) {
                // do sth 
            }
        }
```

**Comment by alvarotrigo** [comment] 2018-07-25 18:23
On page load `origin` will always be null. You can use `destination` for that case.
You should check for origin before using it:

```javascript
afterLoad: function (origin, destination, direction) {
     if(origin){
        console.log(origin.index);
     }
     // if it's page load
     else{
        console.log(destination);
    }
```

**Comment by alvarotrigo** [comment] 2018-07-25 18:25
> It worked without Vue

Should be exactly the same with only fullpage.js

**Comment by desiboli** [comment] 2018-07-28 10:42
Hi I am having the same error message, and I don't understand why! I would appreciate your help!

I cloned this repo https://github.com/cheulong/vue-fullpage-scroll/tree/master/vue-scroll and it was running smoothly with the following versions:
```
    "fullpage.js": "^2.9.7",
    "vue-fullpage.js": "0.0.1",
```

But when I update to the latest:

```
   "fullpage.js": "^3.0.2",
    "vue-fullpage.js": "0.0.3",
```

I get the following error message:

`Uncaught ReferenceError: fullpage is not defined.`

Thank you in advance!

**Comment by alvarotrigo** [comment] 2018-07-29 22:47
> I cloned this repo https://github.com/cheulong/vue-fullpage-scroll/tree/master/vue-scroll and it was running smoothly with the following versions:

I have nothing to do with that repository. Apparently it was never update for version 3.

Why don't you use this one? The official vue-fullpage wrapper?
https://github.com/alvarotrigo/vue-fullpage.js/

**Comment by alvarotrigo** [comment] 2018-08-01 14:16
Fixed in vue-fullpage.js 0.0.4

**Closed by alvarotrigo** 2018-08-01 14:16 UTC
Labels: Fixed on dev, bug

**Comment by TaiRise** [comment] 2018-10-11 09:59
Hello, i've got the same issue and i have 0.0.6 for vue-fullpage.

Do you know why i still have the issue ?

**Comment by alvarotrigo** [comment] 2018-10-11 23:08
@TaiRise impossible to say without a reproduction of it in codepen, jsfiddle or codesandbox.

**Comment by mevis330** [comment] 2018-10-30 11:43
Same error.  Webpack demo also doesn't not work.

"vue": "^2.5.17",
"vue-fullpage.js": "0.0.7"

`Uncaught ReferenceError: fullpage is not defined
    at Object.<anonymous> (vue-fullpage.js:290)
    at __webpack_require__ (vue-fullpage.js:42)
    at vue-fullpage.js:88
    at vue-fullpage.js:91
    at webpackUniversalModuleDefinition (vue-fullpage.js:15)
    at Object.../node_modules/vue-fullpage.js/dist/vue-fullpage.js (vue-fullpage.js:22)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Module../js/index.js (index.js:1)
    at __webpack_require__ (bootstrap:724)`

**Comment by mevis330** [comment] 2018-10-30 11:46
Same error.  Webpack demo also doesn't work.

"vue": "^2.5.17",
"vue-fullpage.js": "0.0.7"

`Uncaught ReferenceError: fullpage is not defined
    at Object.<anonymous> (vue-fullpage.js:290)
    at __webpack_require__ (vue-fullpage.js:42)
    at vue-fullpage.js:88
    at vue-fullpage.js:91
    at webpackUniversalModuleDefinition (vue-fullpage.js:15)
    at Object.../node_modules/vue-fullpage.js/dist/vue-fullpage.js (vue-fullpage.js:22)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Module../js/index.js (index.js:1)
    at __webpack_require__ (bootstrap:724)`
