### ISSUE TITLE
beforeDestroy hook    removeEventListener   undefined

### ISSUE THREAD

**Issue by onyz4x** [alvarotrigo/vue-fullpage.js#44] opened 2018-08-09 03:38 UTC
![image](https://user-images.githubusercontent.com/15812120/43876627-8ddad32a-9bc8-11e8-9aac-9f2c36be1a63.png)

happens when use router-link jump out of this page

**Comment by alvarotrigo** [comment] 2018-08-09 10:58
Can you please detail the step by step guide to reproduce your issue?

**Comment by onyz4x** [comment] 2018-08-09 15:01
i start a new project for this new issue,it shows again

vue-cli 2.9.6
vue init webpack project
standard


HelloWorld.vue
```
<template>
  <div>
    <full-page ref="fullpage" :options="options" id="fullpage">
      <div class="section">
        First section ...
      </div>
      <div class="section">
        Second section ...
        <router-link to="/otherPage">go to other page</router-link>
      </div>
      <div class="section">
        page3 section ...
      </div>
    </full-page>
  </div>
</template>

<script>

export default {
  name: 'HelloWorld',
  data () {
    return {
      options: {
        anchors: ['page1', 'page2', 'page3'],
        sectionsColor: ['#41b883', '#ff5f45', '#0798ec']
      },
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

```


main.js
```
import Vue from 'vue'
import VueFullPage from 'vue-fullpage.js'
import App from './App'
import router from './router'

Vue.config.productionTip = false

Vue.use(VueFullPage)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})
```

router/index.js

```
import Vue from 'vue'
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld'
import otherPage from '@/components/otherPage'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {
      path: '/otherPage',
      name: 'otherPage',
      component: otherPage
    }
  ]
})
```


click the link 
`<router-link to="/otherPage">go to other page</router-link>`

issue does show

**Comment by alvarotrigo** [comment] 2018-08-09 16:34
Can you please replace the component's `src/Fullpage.vue` file for the one [in the dev branch](https://github.com/alvarotrigo/vue-fullpage.js/blob/dev/src/FullPage.vue)?

Can you let me know if the issue is solved now?

**Comment by onyz4x** [comment] 2018-08-10 01:03
still happens
![image](https://user-images.githubusercontent.com/15812120/43933436-3d890a18-9c7c-11e8-949b-af387febdb69.png)
![image](https://user-images.githubusercontent.com/15812120/43933442-4576d070-9c7c-11e8-825a-36b330e71f6c.png)

**Comment by alvarotrigo** [comment] 2018-08-10 07:56
Can you please try with the normal fullPage file instead of with the extensions one? 
Use the unminified version so I can see exactly in which line it's breaking.

**Comment by onyz4x** [comment] 2018-08-10 08:32
your unminified version of fullPage.vue 
import fullpage from 'fullpage.js/dist/fullpage.extensions.min'
![image](https://user-images.githubusercontent.com/15812120/43947510-e47dd7de-9cba-11e8-84d7-fba4cdec8902.png)
![image](https://user-images.githubusercontent.com/15812120/43947539-f942c6f2-9cba-11e8-8830-2c17bfff1e7e.png)

**Comment by alvarotrigo** [comment] 2018-08-13 10:56
Is there anyway I can reproduce this without using router?  On any of the demos available?

**Comment by onyz4x** [comment] 2018-08-13 11:01
it only happens when i use router...

**Comment by alvarotrigo** [comment] 2018-08-13 11:03
Executing `fullpage_api.destroy('all');` seems to be working fine in any of the demos. Which is basically what `beforeDestroy` triggers.

Try replacing on the vue component at `src/Fullpage.vue`:

```javascript
  import fullpage from 'fullpage.js/dist/fullpage.extensions.min';
```

For
```javascript
  import fullpage from 'fullpage.js/dist/fullpage';
```

This way we will be able to see in which precise line the fullpage.js script is failing and have it easier to detect the issue.

**Comment by onyz4x** [comment] 2018-08-13 12:52
![image](https://user-images.githubusercontent.com/15812120/44032769-b9b726fe-9f3a-11e8-9061-b686cc40c9b2.png)

**Comment by onyz4x** [comment] 2018-08-13 12:54
![image](https://user-images.githubusercontent.com/15812120/44032837-f7a09d74-9f3a-11e8-876f-7a7f8ed498db.png)

**Comment by alvarotrigo** [comment] 2018-08-13 12:57
So... you are saying this only happens on mobile / touch devices?

**Comment by alvarotrigo** [comment] 2018-08-13 12:59
Sounds like you are changing the DOM structure before even removing fullpage.js or the vue-fullpage.js component.
Therefore it is failing as the elements it tries to look for won't exist.

**Comment by onyz4x** [comment] 2018-08-13 13:02
Uh.... seems like it is ,   i run it on chrome mobile device mode
![image](https://user-images.githubusercontent.com/15812120/44033161-1c4e4ae4-9f3c-11e8-8717-b6942918ddf3.png)

**Comment by alvarotrigo** [comment] 2018-08-13 13:03
Take a look at the DOM. Use some breakpoint and try to see why it is being modified before destroying the component.

**Comment by fanchaot** [comment] 2018-08-23 08:39
I also encountered the same error. Is this problem solved? Only when the mobile terminal reports an error when switching the group price.

**Comment by onyz4x** [comment] 2018-08-23 11:03
没有解决，我自己直接用vue把功能写了，作者好懒的

**Comment by fanchaot** [comment] 2018-08-23 11:06
只有移动端会  组件切换的时候   DOM 销毁不了  也不知道是哪个节点报错  也没有相关的配置

**Comment by alvarotrigo** [comment] 2018-08-23 11:35
@onyz4x I'll remove your comment, as it is inappropriate. 
If you think it is so easy to solve, why don't you just provide a pull request with the solution yourself? That's the whole purpose of being "open sourced".

**Comment by alvarotrigo** [comment] 2018-08-23 11:37
@fanchaot if you can provide me a way to reproduce the error then I'll be able to help.

**Comment by fanchaot** [comment] 2018-08-24 03:11
@alvarotrigo 
![image](https://user-images.githubusercontent.com/32870484/44562868-1ab40480-a78e-11e8-9482-9f01658fdc87.png)
This is a fullpage component, which is reported incorrectly when I switch routes in the component on the mobile side.

Error message   
![image](https://user-images.githubusercontent.com/32870484/44562938-7aaaab00-a78e-11e8-86b8-fcc098aeecbf.png)

**Comment by onyz4x** [comment] 2018-08-24 04:39
@alvarotrigo  didn't  I provide you the way to reproduce the error ?

**Comment by fanchaot** [comment] 2018-08-28 09:06
@alvarotrigo    I hope to get a solution. The mobile terminal jumps from fullpage to other components. This error occurs. Very good to find.

**Comment by alvarotrigo** [comment] 2018-08-28 12:09
I'll investigate it whenever I have the time for it. 
I'm currently away from home on holidays (as I was when the issue was open), therefore don't have much time for it now.
But of course, if you have any suggestions to solve it, please feel free to create a pull request for it ;)

**Comment by alvaromoo** [comment] 2018-09-06 14:54
If you disable the functionality of fullpage.js on mobile try to wrap your content with a component that loads the fullpage component conditionally.

I solved the problem like this

`<template>

  <full-page :options="options" id="fullpage" v-if="!isMobile">
    <slot />
  </full-page>

  <div v-else>
    <slot />
  </div>

</template>

<script>

import { mapState } from 'vuex';

export default {
  name: 'HomeContent',
  props: {
    options: {
      type: Object,
    },
  },
  computed: {
    ...mapState([
      'isMobile',
    ]),
  },
};

</script>
`

You just need to detect mobile user agent and keep it in your store to check the device.

**Comment by alvaromoo** [comment] 2018-09-06 15:00
If you disable the functionality of fullpage.js on mobile try to wrap your content with a component that loads the fullpage component conditionally.

I solved the problem like this https://codepen.io/alvaromloycus/pen/gdGWjK

You just need to detect mobile user agent and keep it in your store to check the device.

**Comment by fanchaot** [comment] 2018-09-07 03:09
@alvaromoo  
I am not going to disable the fullpage.js function on the mobile side, but I am getting an error when using the fullpage.js jump page on the mobile side.

**Comment by alvarotrigo** [comment] 2018-09-07 14:33
If you guys can provide me the full reproduction of it on a repository of some kind or CodeSandBox / [Codepen](https://codepen.io/alvarotrigo/pen/zpQmwq), that will make things easier for me.

I'm not a vue.js expert and not used to work with it.

**Comment by grantmx** [comment] 2018-09-17 10:53
This is actually happening using AngularJS/ui-router on mobile using vanilla version of fullpage.js as well.  

Steps to reproduce:
1. Set up fullpageJS in a type of "index" page route as normal
2. We then navigate to the next route where we aren't using fullpageJS and then navigate back to the index page route
3. However, in order to re-instantiate fullpage JS after we swap routes we have to first destroy it in the index page route. ```.destroy();``` and then reinitialize it.  This is where the error occurs.

When ```$(WRAPPER_SEL)[0]``` isn't selecting the wrapper class ```".fullpage-wrapper"```  in the ```removeTouchHandler()``` method because it no longer exists on the DOM.

I found that if I wrap with with a condition it fixes the problem for me,

```
if($(WRAPPER_SEL)[0]){
   $(WRAPPER_SEL)[0].removeEventListener(events.touchstart, touchStartHandler);
   $(WRAPPER_SEL)[0].removeEventListener(events.touchmove, touchMoveHandler, {passive: false});
}
```

and then once I'm ready i reinitialize fullpagejs and it works as normal. 

I figure that since the only 2 methods that the selector is used are ```addTouchHandler``` and ```removeTouchHandler``` then both could use a wrap since the ```removeEventListener`` throws a devastating error.

It also may be better to use Try/Catch here rather than a stiff condition.

**Comment by alvarotrigo** [comment] 2018-09-17 11:50
> Hey @alvarotrigo - This is actually happening using AngularJS/ui-router on mobile using vanilla version of fullpage.js as well.

If your issue is non vue related, then you should then open the issue on the [fullpage.js github repo](https://github.com/alvarotrigo/fullPage.js).

**Comment by alvarotrigo** [comment] 2018-09-17 11:53
@grantmx in any case, sounds like you are calling the destroy function when fullpage.js doesn't even exist. There's no reason for `WRAPPER_SEL ` to not exist on removeTouchHandler. As the classes are only removed on `destroyStructure`, which is only called at the end of the `destroy` function.

**Comment by grantmx** [comment] 2018-09-17 12:10
> If your issue is non vue related, then you should then open the issue on the [fullpage.js github repo](https://github.com/alvarotrigo/fullPage.js).

@alvarotrigo  - Understood.  I just wanted to let the VUE folk know its happening in both modules and the work around.

**Comment by grantmx** [comment] 2018-09-17 12:30
> @grantmx in any case, sounds like you are calling the destroy function when fullpage.js doesn't even exist. There's no reason for `WRAPPER_SEL` to not exist on removeTouchHandler. As the classes are only removed on `destroyStructure`, which is only called at the end of the `destroy` function.

Kind of and I fundamentally agree with you, but I've seen fullpageJS linger for whatever reason even after changing routes, so I fully destroy it again as I have to rebuild my DOM, but upon destroying it only on mobile, the exception is thrown.

I could be my setup and maybe I'm missing something, but nonetheless that's what I've seen.

**Comment by alvarotrigo** [comment] 2018-09-17 12:36
In that case the solution should be something like this:

```javascript
function destroy(){
    if(!hasClass($('html'), ENABLED)){ 
       return; 
   }
   ....
}
``` 
In order to prevent executing anything within the function if the element doesn't exist.

**Comment by grantmx** [comment] 2018-09-17 12:39
@alvarotrigo Yep.  That also makes sense to just bounce them out rather than wrap the method with a condition.

**Comment by Cai3ra** [comment] 2018-09-27 14:20
Hi, @alvarotrigo. I sent you a PR about this. 
Please, verify there.

**Comment by alvarotrigo** [comment] 2018-09-27 14:47
@Cai3ra where? Can you send the link?

**Comment by Cai3ra** [comment] 2018-09-27 14:50
@alvarotrigo, there you go: https://github.com/alvarotrigo/fullPage.js/pull/3426

**Comment by alvarotrigo** [comment] 2018-09-27 14:53
@Cai3ra sorry I missed it on my inbox! :D

**Comment by alvarotrigo** [comment] 2018-10-10 10:46
This bug has been fixed on the latest vue-fullpage.js version 0.0.6.

However, @Cai3ra, I still waiting for your pull request on the fullPage.js repo. (I've manually changed the fullpage dependency for vue-fullpage.js, but changes still need to be done on the real fullpage.j repo)

**Closed by alvarotrigo** 2018-10-10 10:46 UTC
Labels: Fixed on dev, Reproduction required
